// Generated by CoffeeScript 1.6.3
var Model, umd;

Model = (function() {
  function Model() {}

  Model.prototype._data = {};

  Model.prototype.get = function(key) {};

  Model.prototype.set = function(key, value) {};

  Model.prototype.setnx = function(key, value) {};

  return Model;

})();

umd = function(name, factory) {
  if (typeof exports === 'object') {
    return module.exports = factory;
  } else if (typeof define === 'function' && define.amd) {
    return define(name, [], function() {
      return factory;
    });
  } else {
    return this[name] = factory;
  }
};

umd('umodel', Model);
